version: 2

references:
  workspace_root: &workspace_root ~/exchange-connector

  timezone: &timezone "/usr/share/zoneinfo/Europe/London"

  node_image: &node_image circleci/node:8.10.0-stretch

  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

jobs:
  setup:
    working_directory: *workspace_root
    environment:
      TZ: *timezone
    docker:
      - image: *node_image
    steps:
      - checkout
      - run: yarn
      - persist_to_workspace:
          root: *workspace_root
          paths:
            - node_modules
  test:
    working_directory: *workspace_root
    environment:
      TZ: *timezone
    docker:
      - image: *node_image
    steps:
      - checkout
      - *attach_workspace
      - run: yarn test:unit
  build:
    working_directory: *workspace_root
    environment:
      TZ: *timezone
    docker:
      - image: *node_image
    steps:
      - checkout
      - *attach_workspace
      - run: yarn test:unit
workflows:
  version: 2
  setup_and_test:
    jobs:
      - setup
      - test:
          requires:
            - setup
      - build:
          requires:
            - setup
            - test
